name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y openjdk-17-jdk wget unzip
        sudo apt install -y build-essential git python3-dev ffmpeg libsdl2-dev
        sudo apt install -y libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev
        sudo apt install -y libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev
        sudo apt install -y zlib1g-dev
        
    - name: Set JAVA_HOME
      run: |
        echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV
        echo "/usr/lib/jvm/java-17-openjdk-amd64/bin" >> $GITHUB_PATH
        
    - name: Cache pip packages
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Cache buildozer global directory
      uses: actions/cache@v4
      with:
        path: ~/.buildozer
        key: ${{ runner.os }}-buildozer-${{ hashFiles('**/*.spec') }}
        restore-keys: |
          ${{ runner.os }}-buildozer-
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer==1.5.0
        pip install python-for-android==2024.1.21
        pip install kivymd==2.0.1.dev0
        pip install kivy[base]==2.3.1
        pip install certifi requests urllib3 charset-normalizer idna
        
    - name: Verify buildozer installation
      run: |
        buildozer --version
        python -c "import kivymd; print('KivyMD version:', kivymd.__version__)"
        
    - name: Build APK
      run: |
        echo "Starting APK build..."
        buildozer android debug
        
    - name: List generated files
      run: |
        echo "Contents of bin directory:"
        ls -la bin/ || echo "No bin directory found"
        find . -name "*.apk" -type f || echo "No APK files found"
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: lista-compras-apk
        path: |
          bin/*.apk
        retention-days: 30
        
    - name: Upload build logs
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-logs
        path: |
          .buildozer/
        retention-days: 7
